name: Run Solr Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Load Schema of Solr
        run: |
          docker run -d --name solr -p 2020:8983 solr:8 -DzkRun;
          sleep 10s;
          docker exec -i solr sh < .github/setups/cont.sh;
          curl http://localhost:2020/solr/customer/query -d 'q=*:*'
          curl -X POST -H 'Content-Type: application/json' 'http://localhost:2020/solr/customer/update/json/docs?commit=true' --data-binary '

            {
             "sell-by":"me"
            }
          '
          curl http://localhost:2020/solr/customer/query -d 'q=*:*'





