name: Run Solr Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Load Schema of Solr
        run: |
          docker run --name solr -p 2020:8983 solr:8 -DzkRun;
          sleep 10s;
          docker exec -i solr sh < .github/setups/cont.sh;